// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWgunMFIIJceMeE4VdH0w8U-A6glM6lo',
    appId: '1:807383020417:web:409b7107007db0dd1aee80',
    messagingSenderId: '807383020417',
    projectId: 'biryani-by-flame-433bf',
    authDomain: 'biryani-by-flame-433bf.firebaseapp.com',
    storageBucket: 'biryani-by-flame-433bf.firebasestorage.app',
    measurementId: 'G-WMJBD8Q3G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVPR6TIDIyb_zJdezvyvi1i1LxiowZ_oM',
    appId: '1:807383020417:android:8eca69fbfecc18a41aee80',
    messagingSenderId: '807383020417',
    projectId: 'biryani-by-flame-433bf',
    storageBucket: 'biryani-by-flame-433bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSoC_YdWonvjqmtJsnuP-EJPXjlCQoYSM',
    appId: '1:807383020417:ios:338a6e166d9b63951aee80',
    messagingSenderId: '807383020417',
    projectId: 'biryani-by-flame-433bf',
    storageBucket: 'biryani-by-flame-433bf.firebasestorage.app',
    iosBundleId: 'com.example.fyroInvoicing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSoC_YdWonvjqmtJsnuP-EJPXjlCQoYSM',
    appId: '1:807383020417:ios:338a6e166d9b63951aee80',
    messagingSenderId: '807383020417',
    projectId: 'biryani-by-flame-433bf',
    storageBucket: 'biryani-by-flame-433bf.firebasestorage.app',
    iosBundleId: 'com.example.fyroInvoicing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqWgunMFIIJceMeE4VdH0w8U-A6glM6lo',
    appId: '1:807383020417:web:cbbdc69a2cbac3521aee80',
    messagingSenderId: '807383020417',
    projectId: 'biryani-by-flame-433bf',
    authDomain: 'biryani-by-flame-433bf.firebaseapp.com',
    storageBucket: 'biryani-by-flame-433bf.firebasestorage.app',
    measurementId: 'G-15DE4FK3M9',
  );
}
